"""PSUR report generator — converts extraction data to regulatory reports.

Produces a Periodic Safety Update Report (PSUR-style) from MaudeSignal
extraction data.  Joins Skill #1 (maude-narrative-extractor) and Skill #4
(ai-failure-mode-classifier) results, computes aggregate statistics, and
renders both a Markdown file and an HTML/PDF via jinja2 + weasyprint.

PDF generation is best-effort: if weasyprint is unavailable the result dict
carries ``pdf_path=None`` and no exception is raised.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from jinja2 import BaseLoader, Environment

from maudesignal.storage.database import Database

# ---------------------------------------------------------------------------
# HTML template (jinja2)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PSUR — {{ product_code }} — {{ start_date }} to {{ end_date }}</title>
<style>
  body{font-family:Arial,Helvetica,sans-serif;line-height:1.6;margin:40px;color:#222}
  h1{color:#8b0000;border-bottom:3px solid #8b0000;padding-bottom:6px}
  h2{color:#333;border-bottom:1px solid #ccc;padding-bottom:4px;margin-top:28px}
  .disclaimer{background:#fff8dc;border:2px solid #f0a500;padding:12px 16px;
               border-radius:4px;margin:16px 0;font-weight:bold}
  .metrics{display:flex;gap:16px;flex-wrap:wrap;margin:16px 0}
  .metric{background:#f5f5f5;border:1px solid #ddd;border-radius:6px;
           padding:14px 20px;text-align:center;min-width:110px}
  .metric .val{font-size:1.9em;font-weight:bold;color:#8b0000}
  .metric .lbl{font-size:.8em;color:#666;margin-top:2px}
  table{border-collapse:collapse;width:100%;margin:12px 0}
  th{background:#8b0000;color:#fff;padding:8px 12px;text-align:left}
  td{border:1px solid #ddd;padding:7px 12px}
  tr:nth-child(even){background:#fafafa}
  .report-ids{font-size:.8em;columns:3;column-gap:16px}
  .report-ids li{break-inside:avoid}
  footer{margin-top:36px;font-size:.75em;color:#999;
          border-top:1px solid #eee;padding-top:8px}
</style>
</head>
<body>

<h1>Periodic Safety Update Report (PSUR)</h1>

<div class="disclaimer">
  &#9888; <strong>REGULATORY DISCLAIMER</strong><br>
  This report is a computational signal-surfacing aid generated by MaudeSignal.
  Every finding requires independent human regulatory review before any regulatory
  action. MaudeSignal is NOT an FDA-cleared device and is NOT clinical decision
  support.
</div>

<h2>1. Executive Summary</h2>
<p>
  This report covers <strong>{{ stats.total }}</strong> MAUDE adverse event
  extraction(s) for product code <strong>{{ product_code }}</strong> extracted
  between <strong>{{ start_date }}</strong> and <strong>{{ end_date }}</strong>.
  Of these, <strong>{{ stats.ai_related_count }}
  ({{ "%.1f"|format(stats.ai_related_pct) }}%)</strong> were flagged as
  potentially AI-related.
</p>

<div class="metrics">
  <div class="metric">
    <div class="val">{{ stats.total }}</div>
    <div class="lbl">Total events</div>
  </div>
  <div class="metric">
    <div class="val">{{ stats.ai_related_count }}</div>
    <div class="lbl">AI-related</div>
  </div>
  <div class="metric">
    <div class="val">{{ "%.0f"|format(stats.ai_related_pct) }}%</div>
    <div class="lbl">AI rate</div>
  </div>
  <div class="metric">
    <div class="val">{{ "%.2f"|format(stats.avg_confidence) }}</div>
    <div class="lbl">Avg confidence</div>
  </div>
  <div class="metric">
    <div class="val">{{ stats.requires_review_count }}</div>
    <div class="lbl">Needs review</div>
  </div>
</div>

<h2>2. Reporting Period &amp; Scope</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  <tr><td>Product Code</td><td>{{ product_code }}</td></tr>
  <tr><td>Extraction window</td><td>{{ start_date }} — {{ end_date }}</td></tr>
  <tr><td>Data source</td><td>FDA MAUDE (via openFDA API)</td></tr>
  <tr><td>Skill used</td><td>maude-narrative-extractor v{{ skill_version }}</td></tr>
  <tr><td>Report generated</td><td>{{ generated_at }}</td></tr>
  <tr><td>Total extractions</td><td>{{ stats.total }}</td></tr>
</table>

<h2>3. Severity Distribution</h2>
<table>
  <tr><th>Severity</th><th>Count</th><th>Percent</th></tr>
  {% for sev, cnt in stats.severity_breakdown.items() | sort %}
  <tr>
    <td>{{ sev.replace("_", " ").title() }}</td>
    <td>{{ cnt }}</td>
    <td>{{ "%.1f"|format(cnt / stats.total * 100) }}%</td>
  </tr>
  {% endfor %}
</table>

<h2>4. AI-Related Failure Analysis</h2>
<p>
  <strong>{{ stats.ai_related_count }}</strong> of {{ stats.total }}
  extraction(s) ({{ "%.1f"|format(stats.ai_related_pct) }}%) were flagged
  as AI-related by the extraction model.
</p>

{% if stats.failure_mode_breakdown %}
<h3>4.1 AI Failure Mode Categories (Skill #4)</h3>
<table>
  <tr><th>Failure Mode Category</th><th>Count</th><th>Percent</th></tr>
  {% for mode, cnt in stats.failure_mode_breakdown.items() | sort(attribute=1, reverse=True) %}
  <tr>
    <td>{{ mode.replace("_", " ").title() }}</td>
    <td>{{ cnt }}</td>
    <td>{{ "%.1f"|format(cnt / stats.total * 100) }}%</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

<h2>5. Drift &amp; Monitoring Signals</h2>
<p>
  Confidence scores are monitored via KS (Kolmogorov-Smirnov) test and PSI
  (Population Stability Index). Run
  <code>maudesignal drift --product-code {{ product_code }}</code> for current
  drift statistics. PSI &gt; 0.25 or KS p-value &lt; 0.05 warrants escalation.
</p>
<p>
  Average extraction confidence for this cohort:
  <strong>{{ "%.3f"|format(stats.avg_confidence) }}</strong> / 0.95 max.
</p>

<h2>6. Recommendations for Human Review</h2>
<ol>
  <li><strong>Priority events:</strong> {{ stats.requires_review_count }} extraction(s)
      are flagged <code>requires_review=True</code> and should receive expedited
      human assessment.</li>
  <li><strong>AI failure clusters:</strong> Group the AI-related events by failure
      mode category and cross-reference with device software versions and update
      dates.</li>
  <li><strong>Trend monitoring:</strong> If the AI-related rate increases &gt;10 pp
      month-over-month, escalate to the quality/safety team.</li>
  <li><strong>Root cause:</strong> Top failure modes warrant engineering review of
      design inputs, training data, and validation datasets.</li>
  <li><strong>Regulatory engagement:</strong> Critical signal clusters may trigger
      21 CFR 803 / 806 notification obligations — consult regulatory counsel.</li>
</ol>

<h2>7. Methodology</h2>
<table>
  <tr><th>Component</th><th>Detail</th></tr>
  <tr><td>Data source</td><td>FDA MAUDE (openFDA public API)</td></tr>
  <tr><td>Skill #1</td><td>maude-narrative-extractor — structured field extraction</td></tr>
  <tr><td>Skill #3</td><td>severity-triage — FDA MDR severity assignment</td></tr>
  <tr><td>Skill #4</td><td>ai-failure-mode-classifier — 11-category AI taxonomy</td></tr>
  <tr><td>Validation</td><td>JSON Schema + Pydantic 2 output validation</td></tr>
  <tr><td>Storage</td><td>SQLite (SQLAlchemy 2); append-only audit log</td></tr>
  <tr><td>Disclaimer</td>
      <td>Computational aid — all findings require human verification</td></tr>
</table>

<h2>8. Source Report IDs</h2>
<p>All {{ stats.total }} MAUDE report IDs included in this analysis:</p>
<ul class="report-ids">
  {% for rid in report_ids %}
  <li>{{ rid }}</li>
  {% endfor %}
</ul>

<footer>
  MaudeSignal PSUR — generated {{ generated_at }} —
  NOT an FDA-cleared device — NOT clinical decision support
</footer>

</body>
</html>
"""

_JINJA_ENV = Environment(loader=BaseLoader(), autoescape=True)

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _ensure_utc(ts: datetime) -> datetime:
    return ts if ts.tzinfo else ts.replace(tzinfo=UTC)


def _parse_extractor_row(output_json: str) -> dict[str, Any]:
    try:
        return dict(json.loads(output_json))
    except (json.JSONDecodeError, ValueError):
        return {}


def _calculate_stats(records: list[dict[str, Any]]) -> dict[str, Any]:
    total = len(records)
    ai_related = sum(1 for r in records if r.get("ai_related_flag"))
    requires_review = sum(1 for r in records if r.get("requires_review"))

    severity_breakdown: dict[str, int] = {}
    for r in records:
        sev = str(r.get("severity") or "unknown")
        severity_breakdown[sev] = severity_breakdown.get(sev, 0) + 1

    failure_mode_breakdown: dict[str, int] = {}
    for r in records:
        fm = r.get("failure_mode_category")
        if fm and fm != "not_ai_related":
            failure_mode_breakdown[str(fm)] = failure_mode_breakdown.get(str(fm), 0) + 1

    confs = [float(r["confidence_score"]) for r in records if r.get("confidence_score") is not None]
    avg_conf = sum(confs) / len(confs) if confs else 0.0

    return {
        "total": total,
        "ai_related_count": ai_related,
        "ai_related_pct": (ai_related / total * 100.0) if total else 0.0,
        "requires_review_count": requires_review,
        "severity_breakdown": severity_breakdown,
        "failure_mode_breakdown": failure_mode_breakdown,
        "avg_confidence": avg_conf,
    }


# ---------------------------------------------------------------------------
# PSURGenerator
# ---------------------------------------------------------------------------


class PSURGenerator:
    """Generate PSUR-style periodic safety reports from extraction data."""

    def __init__(self, db: Database) -> None:
        """Initialize the generator with a Database instance."""
        self._db = db

    def generate(
        self,
        product_code: str,
        start_date: str,
        end_date: str,
        output_dir: str | Path = "reports",
    ) -> dict[str, Any]:
        """Generate a PSUR for a product code over an extraction date range.

        Args:
            product_code: FDA 3-character product code (e.g. ``"QIH"``).
            start_date: Start of extraction window, ``YYYY-MM-DD`` (inclusive).
            end_date: End of extraction window, ``YYYY-MM-DD`` (inclusive).
            output_dir: Directory to write output files (created if absent).

        Returns:
            Dict with keys ``markdown_path`` (str), ``pdf_path`` (str or None),
            ``record_count`` (int), ``ai_related_count`` (int).

        Raises:
            ValueError: No extractions found for the given product code / window.
        """
        start_dt = datetime.strptime(start_date, "%Y-%m-%d").replace(tzinfo=UTC)
        end_dt = datetime.strptime(end_date, "%Y-%m-%d").replace(tzinfo=UTC) + timedelta(days=1)

        extractor_rows = self._db.list_extractions(
            product_code=product_code,
            skill_name="maude-narrative-extractor",
        )
        filtered = [r for r in extractor_rows if start_dt <= _ensure_utc(r.extraction_ts) < end_dt]

        if not filtered:
            raise ValueError(
                f"No maude-narrative-extractor extractions found for product_code="
                f"{product_code!r} between {start_date} and {end_date}. "
                "Run `maudesignal extract` first."
            )

        # Build per-record dicts from Skill #1 output_json.
        records: list[dict[str, Any]] = []
        skill_version = filtered[0].skill_version
        for row in filtered:
            payload = _parse_extractor_row(row.output_json)
            records.append(
                {
                    "maude_report_id": row.maude_report_id,
                    "extraction_ts": row.extraction_ts,
                    "confidence_score": row.confidence_score,
                    "requires_review": row.requires_review,
                    "ai_related_flag": bool(payload.get("ai_related_flag") or False),
                    "severity": str(payload.get("severity") or "unknown"),
                    "failure_mode": payload.get("failure_mode"),
                    "failure_mode_category": None,  # filled below from Skill #4
                }
            )

        # Enrich with Skill #4 (ai-failure-mode-classifier) if available.
        classifier_rows = self._db.list_extractions(
            product_code=product_code,
            skill_name="ai-failure-mode-classifier",
        )
        classifier_lookup: dict[str, str] = {}
        for row in classifier_rows:
            p = _parse_extractor_row(row.output_json)
            fmc = p.get("failure_mode_category")
            if fmc:
                classifier_lookup[row.maude_report_id] = str(fmc)

        for rec in records:
            rec["failure_mode_category"] = classifier_lookup.get(rec["maude_report_id"])

        stats = _calculate_stats(records)

        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
        stem = f"{product_code}_PSUR_{start_date}_{end_date}_{timestamp}"
        generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

        template_ctx: dict[str, Any] = {
            "product_code": product_code,
            "start_date": start_date,
            "end_date": end_date,
            "stats": stats,
            "records": records,
            "report_ids": [r["maude_report_id"] for r in records],
            "skill_version": skill_version,
            "generated_at": generated_at,
        }

        # --- Markdown ---
        md_content = _render_markdown(template_ctx)
        md_path = out / f"{stem}.md"
        md_path.write_text(md_content, encoding="utf-8")

        # --- PDF (best-effort) ---
        pdf_path: str | None = None
        html_content = _JINJA_ENV.from_string(_HTML_TEMPLATE).render(**template_ctx)
        try:
            import weasyprint

            pdf_bytes: bytes = weasyprint.HTML(string=html_content).write_pdf()
            pdf_file = out / f"{stem}.pdf"
            pdf_file.write_bytes(pdf_bytes)
            pdf_path = str(pdf_file)
        except (ImportError, OSError):
            # weasyprint requires system GTK/Cairo libs that may not be present.
            pass

        return {
            "markdown_path": str(md_path),
            "pdf_path": pdf_path,
            "record_count": len(records),
            "ai_related_count": stats["ai_related_count"],
        }


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------


def _render_markdown(ctx: dict[str, Any]) -> str:
    stats = ctx["stats"]
    pc = ctx["product_code"]
    start = ctx["start_date"]
    end = ctx["end_date"]
    generated_at = ctx["generated_at"]
    skill_version = ctx["skill_version"]

    lines: list[str] = [
        "# Periodic Safety Update Report (PSUR)",
        "",
        "> **REGULATORY DISCLAIMER** — This report is a computational"
        " signal-surfacing aid generated by MaudeSignal. Every finding"
        " requires independent human regulatory review before any regulatory"
        " action. MaudeSignal is NOT an FDA-cleared device and is NOT clinical"
        " decision support.",
        "",
        "---",
        "",
        "## 1. Executive Summary",
        "",
        f"This report covers **{stats['total']}** MAUDE adverse event"
        f" extraction(s) for product code **{pc}** extracted between"
        f" **{start}** and **{end}**. Of these,"
        f" **{stats['ai_related_count']}"
        f" ({stats['ai_related_pct']:.1f}%)** were flagged as potentially"
        " AI-related.",
        "",
        "---",
        "",
        "## 2. Reporting Period & Scope",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Product Code | {pc} |",
        f"| Extraction window | {start} — {end} |",
        "| Data source | FDA MAUDE (via openFDA API) |",
        f"| Skill | maude-narrative-extractor v{skill_version} |",
        f"| Report generated | {generated_at} |",
        f"| Total extractions | {stats['total']} |",
        "",
        "---",
        "",
        "## 3. Severity Distribution",
        "",
        "| Severity | Count | Percent |",
        "|---|---|---|",
    ]

    for sev, cnt in sorted(stats["severity_breakdown"].items()):
        pct = (cnt / stats["total"] * 100) if stats["total"] else 0.0
        lines.append(f"| {sev.replace('_', ' ').title()} | {cnt} | {pct:.1f}% |")

    lines += [
        "",
        "---",
        "",
        "## 4. AI-Related Failure Analysis",
        "",
        f"**{stats['ai_related_count']}** of {stats['total']}"
        f" extraction(s) ({stats['ai_related_pct']:.1f}%) were flagged"
        " as AI-related.",
        "",
    ]

    if stats["failure_mode_breakdown"]:
        lines += [
            "### 4.1 AI Failure Mode Categories (Skill #4)",
            "",
            "| Failure Mode Category | Count | Percent |",
            "|---|---|---|",
        ]
        for mode, cnt in sorted(
            stats["failure_mode_breakdown"].items(), key=lambda x: x[1], reverse=True
        ):
            pct = (cnt / stats["total"] * 100) if stats["total"] else 0.0
            lines.append(f"| {mode.replace('_', ' ').title()} | {cnt} | {pct:.1f}% |")
        lines.append("")

    lines += [
        "---",
        "",
        "## 5. Drift & Monitoring Signals",
        "",
        f"Average extraction confidence: **{stats['avg_confidence']:.3f}** / 0.95 max.",
        "",
        f"Run `maudesignal drift --product-code {pc}` for KS/PSI drift statistics.",
        "",
        "---",
        "",
        "## 6. Recommendations for Human Review",
        "",
        f"1. **Priority review:** {stats['requires_review_count']} extraction(s)"
        " are flagged `requires_review=True` — expedite human assessment.",
        "2. Group AI-related events by failure mode and cross-reference with"
        " device software/firmware versions.",
        "3. If AI-related rate increases >10 pp month-over-month, escalate to"
        " quality/safety team.",
        "4. Top failure modes warrant engineering review of training data and"
        " validation datasets.",
        "5. Critical signal clusters may trigger 21 CFR 803/806 notification"
        " obligations — consult regulatory counsel.",
        "",
        "---",
        "",
        "## 7. Methodology",
        "",
        "| Component | Detail |",
        "|---|---|",
        "| Data source | FDA MAUDE (openFDA public API) |",
        "| Skill #1 | maude-narrative-extractor — structured field extraction |",
        "| Skill #3 | severity-triage — FDA MDR severity assignment |",
        "| Skill #4 | ai-failure-mode-classifier — 11-category AI taxonomy |",
        "| Validation | JSON Schema + Pydantic 2 |",
        "| Storage | SQLite (SQLAlchemy 2); append-only audit log |",
        "| Disclaimer | Computational aid — all findings require human verification |",
        "",
        "---",
        "",
        "## 8. Source Report IDs",
        "",
        f"All {stats['total']} MAUDE report IDs included in this analysis:",
        "",
    ]

    for i, rid in enumerate(ctx["report_ids"], 1):
        lines.append(f"{i}. {rid}")

    lines += [
        "",
        "---",
        "",
        f"*MaudeSignal PSUR — generated {generated_at}*  ",
        "*NOT an FDA-cleared device — NOT clinical decision support*",
    ]

    return "\n".join(lines)
